#!/usr/bin/env node

var slashbot = require('slashbot')

slashbot({
  name : 'slashbot',
  responders : [
    './responders/shout',
    './responders/search',
    './responders/choose',
    './responders/scusagrassi',
    './responders/cristone',
    './responders/dice'
  ]
},function(err){
  if(err) throw err
  // your bot is now started.
})
