#!/usr/bin/env node

var slashbot = require('slashbot')

slashbot({
  name : 'slashbot',
  responders : [
    './responders/shout',
    './responders/search',
    './responders/choose'
  ]
},function(err){
  if(err) throw err
  // your bot is now started.
})
